apps/pythonbelt/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
  url(r'^$', views.index, name='index'),
  url(r'^login$', views.login, name='login'),
  url(r'^register$', views.register, name='register'),
  url(r'^home$', views.home, name='home'),
  url(r'^logoff$', views.logoff, name='logoff'),
  url(r'^add$', views.add, name='add'),
  url(r'^create$', views.create, name='create'),
  url(r'^travel/destination/(?P<travel_id>\d+)$', views.show, name='show'),
  url(r'^join/(?P<id>\d+)$', views.join, name='join'),
]

pyBelt/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('apps.pythonbelt.urls', namespace='travel')),
]

apps/pythonbelt/models.py
from __future__ import unicode_literals
from django.db import models
from django.core.exceptions import ObjectDoesNotExist
import re
from django.contrib import messages
import bcrypt
from datetime import date
# Create your models here.
class UserManager(models.Manager):
    def register(self, data):
        error = []
            #index 1 of the innerlist, retrieve in views side
        if len(data["first_name"]) < 3 or any(char.isdigit() for char in data["first_name"]):
            error.append('first name must be at least 3 characters and contain no numbers')
        if len(data["last_name"]) < 3 or any(char.isdigit() for char in data["last_name"]):
            error.append('last name must be at least 3 characters and contain no numbers')
        if len(data["username"]) < 3:
            error.append('username must be at least 3 char')
        if len(data["password"]) < 8:
            error.append('incorrect password length')

        user = self.filter(username = data['username']) #check if false

        if user:
            error.append('username taken')
        if data['password'] != data['password_confirm']:
            error.append('please match your passwords')
        if error:
            return (False, error)

        hashed = bcrypt.hashpw(data['password'].encode('utf-8'), bcrypt.gensalt())
        user = self.create(first_name = data["first_name"],last_name = data["last_name"],username = data["username"], password = hashed)
        return (True, user)

    def login(self, data):
        error = []
        user = self.filter(username=data['username'])
        if user:
            if bcrypt.hashpw(data['password'].encode('utf-8'), user[0].password.encode('utf-8')) == user[0].password:
                return (True, user[0])
        error.append("Invalid credentials, please try again")
        return (False, error)

class TravelManager(models.Manager):
    def create_travel(self, form_data, user_id):

        errors = []
        if len(form_data['destination']) < 1:
            errors.append("You must enter a destination")
        if len(form_data['description']) < 1:
            errors.append("You must enter a description")
        if len(form_data['start_date']) < 1:
            errors.append("You must enter a start date")
        if len(form_data['end_date']) < 1:
            errors.append("You must enter a end date")
        if errors:
            return(False, errors)
        else:
            TripSchedule.objects.create(usertrip=User.objects.get(id=user_id),destination=form_data['destination'], description=form_data['description'], start_date=form_data['start_date'],end_date=form_data['end_date'])
            return (True, form_data)

class User(models.Model):
    first_name = models.CharField(max_length=45)
    last_name = models.CharField(max_length=45)
    username = models.CharField(max_length=45)
    password = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = UserManager()

class TripSchedule(models.Model):
    destination = models.CharField(max_length=255)
    description = models.CharField(max_length=255)
    usertrip = models.ForeignKey(User, related_name="usertrip") #this is the foreignkey, look up at create schedule, that's where it will be referenced and used
    travellers = models.ManyToManyField(User, related_name="travellers")
    start_date = models.DateField()
    end_date = models.DateField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = TravelManager()

apps/pythonbelt/views.py
from django.shortcuts import render, redirect, HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.contrib import messages
from models import User, TripSchedule

def index(request):
    return render(request, 'pythonbelt/index.html')

def register(request): #just taking the request object
    user = User.objects.register(request.POST) #user = a tuple, 2 options, (True, user) or (False, errors)
    if user[0]:
        request.session['user'] = {
            'id':user[1].id,
            'first_name':user[1].first_name,
            'last_name':user[1].last_name,
            'username':user[1].username,
        }
        return redirect(reverse('travel:home'))
    #build flash messages here using user[1]
    for error in user[1]: #always going to be referring as user 1 because it's the first user in the list
        messages.error(request, error)
    return redirect(reverse('travel:index'))

def login(request):
    user = User.objects.login(request.POST)
    if user[0]:
        request.session['user'] = {
            'id':user[1].id,
            'first_name':user[1].first_name,
            'last_name':user[1].last_name,
            'username':user[1].username,
        }
        return redirect(reverse('travel:home')) #what this does here is when the log in is successful, it will redirect the user to the home page of the bookreview app
 #flash messages
    for error in user[1]:
        messages.error(request, error)
    return redirect(reverse('travel:index'))

def logoff(request):
    request.session.clear()
    return redirect(reverse('travel:index'))

def home(request):
    user = User.objects.get(id=request.session['user']['id'])
    context={
        'trips_on':TripSchedule.objects.filter(usertrip=user)|TripSchedule.objects.filter(travellers__id=user.id), #what this does is it will get all of the objects in the tripschedule table, and filter it based on the foreign key from the table and get that specific user
        'trips_off':TripSchedule.objects.exclude(usertrip=user).exclude(travellers__id=user.id)
    }
    return render(request, 'pythonbelt/home.html', context)

def add(request):
    return render(request, 'pythonbelt/add.html')

def create(request):
    result = TripSchedule.objects.create_travel(request.POST, request.session['user']['id'])
    if result[0]:
        return redirect(reverse('travel:home'))
    elif result[0] == False:
        errors = result[1]
        for error in errors:
            messages.error(request, error)
        return redirect(reverse('travel:add'))
    else:
        raise ValueError("this should never happen") #this will raise an error if the 1st 2 checks are failing (but it should never happen)

def show(request, travel_id):
    context = {
        'trip':TripSchedule.objects.get(id=travel_id),
    }
    return render(request,'pythonbelt/show.html', context)

def join(request, id):
    trip = TripSchedule.objects.get(id=id)
    user = User.objects.get(id=request.session['user']['id'])
    trip.travellers.add(user)
    return redirect(reverse('travel:home'))

apps/pythonbelt/templates/pythonbelt/add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
<title>Date validations</title>
</head>
    <title>Add Travel Plans</title>
</head>
<body>
<h1>Add a Trip</h1>
{% if messages %}
    {% for message in messages %}
        <p{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</p>
    {% endfor %}
{% endif %}
<form action="{% url 'travel:create' %}" method='post'>
  {% csrf_token %}
    Destination:<input type="text" name='destination'><br>
    Description:<input type="text" name='description'><br>
    Start date<input type = 'date' name='start_date'><br>
    End date<input type = 'date' name='end_date'><br>
    <input type="submit" value="add">
 </form>
 <p><a href="{% url 'travel:logoff' %}">Logoff</a></p>
 <p><a href="{% url 'travel:home' %}">Home</a></p>
</body>
</html>

apps/pythonbelt/templates/pythonbelt/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <a href="{% url 'travel:logoff' %}">Log out</a>
    <a href="{% url 'travel:home' %}">Home</a>
    <h1>Welcome, {{request.session.user.first_name}}</h1>
    <table>
			<tr><th>Destination</th>
				<th>Start Date</th>
				<th>End Date</th>
				<th>Description</th>
			</tr>
			{% for trip in trips_on %}
				<tr>
					<td><a href="{% url 'travel:show' trip.id %}">{{trip.destination}}</a></td>
					<td>{{trip.start_date}}</td>
					<td>{{trip.end_date}}</td>
					<td>{{trip.description}}</td>
				</tr>
			{% endfor %}
		</table>

		<h3>Other trips:</h3>

		<table>
			<tr><th>Creator</th>
				<th>Destination</th>
				<th>Start Date</th>
				<th>End Date</th>
				<th>Description</th>
				<th>Join?</th>
			</tr>
			{% for trip in trips_off %}
				<tr>
					<td>{{trip.usertrip.first_name}}</td>
					<td><a href="{% url 'travel:show' trip.id %}">{{trip.destination}}</a></td>
					<td>{{trip.start_date}}</td>
					<td>{{trip.end_date}}</td>
					<td>{{trip.description}}</td>
					<td><a href="{% url 'travel:join' trip.id %}">Join</a></td>
				</tr>
			{% endfor %}
		</table>
    <a href="{% url 'travel:add' %}">Make a new trip</a>
</body>
</html>

apps/pythonbelt/templates/pythonbelt/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Index page</title>
</head>
<body>
    <h3>WELCOME!</h3>
    {% if messages %}
        {% for message in messages %}
            <p{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</p>
        {% endfor %}
    {% endif %}
    <form action="{% url 'travel:register' %}" method='post'>
      {% csrf_token %}
      First Name:<input type="text" name='first_name'><br>
      Last Name:<input type="text" name='last_name'><br>
      Username:<input type="text" name='username'><br>
      Password<input type="password" name='password'><br>
      Confirm Password<input type="password" name="password_confirm"><br>
      <input type="submit" value="Register"><br>
    </form>
    <form action="{% url 'travel:login' %}" method="post">
      {% csrf_token %}
      <h3>login here</h3>
      Username: <input type="text" name="username"><br>
      Password: <input type="password" name="password"><br>
      <input type="submit" value="Login">
    </form>
</body>
</html>

apps/pythonbelt/templates/pythonbelt/show.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Show Trip</title>
</head>
<body>
<p><a href="{% url 'travel:logoff' %}">Logoff</a></p>
<p><a href="{% url 'travel:home' %}">Home</a></p>
<h1>{{trip.destination}}</h1>
<p>Planned By: {{trip.usertrip.first_name}}</p>
<p>Description: {{trip.description}}</p>
<p>Travel From: {{trip.start_date}}</p>
<p>Travel To: {{trip.end_date}}</p>

<h1>Other users' joining the trip:</h1>
    {% if trip.travellers.all %}
			<ul>
				{% for traveller in trip.travellers.all %}
					<li>{{traveller.first_name}}</li>
				{% endfor %}
			</ul>
    {% endif %}
</body>
</html>